name: Whitelist4Kook
version: '${version}'
main: com.github.yufiriamazenta.whitelist4kook.Whitelist4Kook
api-version: 1.13
folia-supported: true
depend:
  - ParettiaLib
  - KookMC
commands:
  whitelist4kook:
    aliases:
      - wlk
    permission: whitelist4kook.command
